package com.bacon.events;

public enum EventType {
    REVEAL, SOB, BA, OH, OD, AA, EOB, RECYCLE,
    D1_DISCARD_CHANGED, D2_DISCARD_CHANGED,
    P1_PAIR_SELECTED, P2_PAIR_SELECTED,
    BOARD_CHANGED,
    CHARACTER_SELECT, DISCARD_SELECT, PAIR_SELECT, P1_ANTE, P2_ANTE, EFFECT_CHOICE
}
