package com.bacon.gamefiles.events;

public enum EventType {
    REVEAL, SOB, BA, OH, OD, AA, EOB, RECYCLE,
    P1_D1_DISCARD_CHANGED, P1_D2_DISCARD_CHANGED,
    P2_D1_DISCARD_CHANGED, P2_D2_DISCARD_CHANGED,
    PAIRS_SELECTED,
    P1_PAIR_REVEALED, P2_PAIR_REVEALED,
    BOARD_CHANGED, P1_DAMAGE, P2_DAMAGE,
    P1_UA_CHANGE, P2_UA_CHANGE,
    CHARACTER_SELECT, P1_CHAR_SELECTED, P2_CHAR_SELECTED, PRIORITY_ACTIVE, EFFECT_ORDER_SELECT,
    DISCARD_SELECT, PAIR_SELECT, ANTE_SELECT, CLASH_BASE_SELECT, P1_ANTE, P2_ANTE, EFFECT_CHOICE
}
